services:
  - type: web
    name: carbon
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn carbon.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: carbon.settings
      - key: DATABASE_URL
        fromDatabase:
          name: mi-db
          property: connectionString