# Generated by Django 5.2.1 on 2025-07-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport', models.CharField(max_length=50)),
                ('distance', models.FloatField()),
                ('energy', models.FloatField()),
                ('gas', models.FloatField()),
                ('fuel', models.CharField(max_length=50)),
                ('litres', models.FloatField()),
                ('result', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
